// <auto-generated />
using System;
using CodingOnCountry.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodingOnCountry.Migrations
{
    [DbContext(typeof(CodingOnCountryContext))]
    [Migration("20190910172701_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodingOnCountry.Models.Camp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CampAddress");

                    b.Property<string>("CampCommunity");

                    b.Property<DateTime>("CampDate");

                    b.Property<string>("CampEndTime");

                    b.Property<DateTime>("CampStartTime");

                    b.Property<string>("Description");

                    b.Property<string>("EmbededFacebookAlbumLink");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Camp");
                });
#pragma warning restore 612, 618
        }
    }
}
